version: '3.8'

services:

  postgres:
    image: postgres:14.5
    restart: always
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web-server:
    build: .
    command: sleep 3 && bash -c "cd /code/src && alembic upgrade head && gunicorn --name file_service -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:8000 src.main:app"
    ports:
      - ${PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19.3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:root
    depends_on:
      - web-server
    restart: always
